# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: required
###group: deprecated-2017Q2
cache: packages
warnings_are_errors: false,

before_install:
  Rscript -e 'update.packages(ask = FALSE)'

install: 
  - sudo apt-get install -y gcc-6 g++-6
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-6 60 --slave /usr/bin/g++ g++ /usr/bin/g++-6

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-4.8
      - g++-4.8
